### ISSUE TITLE
where is the code

### ISSUE THREAD

**Issue by cnrad** [ScarletAI/ScarletAI#2]
there's just a license and a readme but where's the actual code

**Comment by brandonsaldan** [comment]
where is the code

**Comment by KazutoKashima** [comment]
Currently the code is closed off till I make a few adjustments. I'll be releasing the code on the 9th of this month 👍

**Comment by cnrad** [comment]
Oh OK

**Comment by jacc** [comment]
where is the code

**Comment by KazutoKashima** [comment]
> Currently the code is closed off till I make a few adjustments. I'll be releasing the code on the 9th of this month 👍 

@jacc

**Comment by brandonsaldan** [comment]
Oh OK

**Comment by jacc** [comment]
@brandonsaldan where is the code
